main: # mandatory
  port: 80
  redirect-to-https: boolean
root: # mandatory (will be /)
  redirect: boolean
  to: path1 # must be a node of this yaml
path1: # will be /path1
  to: localhost:8080
path2:
  to: localhost:8081